package amf

const (
	AMF0_NUMBER_TYPE = iota
	AMF0_BOOLEAN_TYPE
	AMF0_STRING_TYPE
	AMF0_OBJECT_TYPE
	AMF0_MOVIECLIP_TYPE
	AMF0_NULL_TYPE
	AMF0_UNDEFINED_TYPE
	AMF0_REFERENCE_TYPE
	AMF0_ECMAARRAY_TYPE
	AMF0_OBJECTEND_TYPE
	AMF0_STRICTARRAY_TYPE
	AMF0_DATE_TYPE
	AMF0_LONGSTRING_TYPE
	AMF0_UNSUPPORTED_TYPE
	AMF0_RECORDSET_TYPE
	AMF0_XML_TYPE
	AMF0_TYPEDOBJECT_TYPE
	AMF0_AMF3DATA_TYPE
)
